### ISSUE TITLE
Why use "cat" to print to screen instead of "print"

### ISSUE THREAD

**Issue by 0xbrayo** [square-lang/Square#1]
Almost all languages use print as the function to print to screen. If u want this language to even stand a chance of going mainstream u need to stick to such conventions. Such a minor detail could be the difference between someone liking or disliking a language. Anyway am not one to criticise a lot, I know it must be super difficult build your own language from scratch.

**Comment by StepfenShawn** [comment]
Thanks for your advice, Square can now use the` print` function:)
