### ISSUE TITLE
Improve the topic (add an image, description and more)

### ISSUE THREAD

**Issue by Panquesito7** [square-lang/Square#4]
I'd like to [curate](https://github.com/github/explore/tree/master/CONTRIBUTING.md?source=add-description-square-lang) the `square-lang` topic with an image,
description and more. I just need permission to use the logo.

Thanks. 🙂

**Comment by StepfenShawn** [comment]
Sounds great! I permited!

**Comment by Panquesito7** [comment]
https://github.com/github/explore/pull/2029

**Comment by Panquesito7** [comment]
Closing this issue as https://github.com/github/explore/pull/2029 was closed ([reason](https://github.com/github/explore/pull/2029#issuecomment-739979167)).
